# Generated by Django 4.2.7 on 2023-12-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('address', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=30)),
                ('timings', models.TimeField()),
                ('likes', models.BigIntegerField()),
                ('contact_info', models.CharField(max_length=40)),
            ],
        ),
    ]
